---
title: "02_clean_data"
format: html
editor: visual
output-file: results/02_clean_data.html
---

# Load libraries

```{r}
#| message: false
library("tidyverse")
```

# Clean Data

## Load data

```{r}
meta_data <- read.csv("../data/01_data_table_load.csv", na = c("", "NA", "N/A"))
disease_label <- read.csv("../data/01_disease_state_vector_load.csv")
```

## Select relevant columns and remove all NAs

```{r}
selected_data <- meta_data |>
  select(-Gene.symbol, -Gene.ID, -UniGene.title, -UniGene.symbol, -UniGene.ID, 
         -Nucleotide.Title, -GI, -GenBank.Accession, -Platform_CLONEID, - Platform_ORF,
         -Platform_SPOTID, -Chromosome.location, -Chromosome.annotation, -X, -ID_REF) |>
  drop_na()
```

```{r}
disease_label <- disease_label |>
  select(-X)
```

## Log2 transformation

```{r}
transformed_data <- selected_data |>
  mutate(across(starts_with("GSM"), log2))
```

## Merge data

The transformed data is merged with the disease_label data.

```{r}

# Pivot Longer
df_long <- transformed_data |> 
  pivot_longer(cols = starts_with("GSM"), names_to = "Sample", values_to = "value")

# Join with disease_label
df_long <- df_long |> 
  left_join(disease_label, by = "Sample") |> 
  mutate(value = as.character(value)) 

# Add disease.state as an Identifyer 
df_label <- df_long |> 
  distinct(Sample, disease.state) |>
  mutate(IDENTIFIER = "disease.state") |> 
  rename(value = disease.state)

# Bind df_long with the disease.state label 
df_combined <- df_long |> 
  select(IDENTIFIER, Sample, value, Gene.title, GO.Function, GO.Process,  GO.Component,GO.Function.ID, GO.Process.ID,GO.Component.ID) |> 
  bind_rows(df_label)

# 5. Pivot wider to get final df
clean_data <- df_combined |> 
  pivot_wider(names_from = Sample, 
              values_from = value,
              values_fn = list)
```

Save the clean data set

Jeg kan ikke gemme clean_data som en csv fil, fordi der opstår nogle lists idet jeg laver pivot_wider til sidst. Det er ikke lykkedes mig endnu at finde ud af hvorfor.

```{r}
write.csv(clean_data, file="../data/02_clean_data.csv")
```
